In [1]:
# Talha Hussain
# Data Science
# Homework Assignment 5 MongoDB Using Movies Dataset and Ratings Dataset and Tags Dataset
# introduction_To_Data_Science_Homework_Assignment_5_MongoDB_Using_Movies_Dataset_And_Ratings_Dataset_And_Tags_Dataset_Problems_2_To_6.ipynb
from pymongo import MongoClient
import pandas as pd
import time

In [2]:
############################################################################################################################
# Problem 3: Write a Program to read the given 3 different Commas-Separated Value Files that includes the Commas-Separated #
# Value CSV File "movies.csv", the Commas-Separated Value CSV File "ratings.csv", and the Commas-Separated Value CSV       #
# File "tags.csv" and then insert all the records into three different collections.                                        #                                                                   
############################################################################################################################
# Create a connection to MongoDB.
client = MongoClient('mongodb://localhost:27017')

# Create a database in MongoDB.
db = client['movie_database']

# Create the three different collections.
movies_collection = db['movies']
ratings_collection = db['ratings']
tags_collection = db['tags']

# Use the "delete_many()" Function for the three different collections to clean out any data already in the three different collections so that 
# they are empty every run.
movies_collection.delete_many({})
ratings_collection.delete_many({})
tags_collection.delete_many({})

# Read the Commas-Separated Value CSV Files "movies.csv", "ratings.csv", and "tags.csv" using the Python Library "pandas".
movies_data_frame = pd.read_csv('movies.csv')
ratings_data_frame = pd.read_csv('ratings.csv')
tags_data_frame = pd.read_csv('tags.csv')

# Convert the Dataframes to a Dictionary using the "to_dict()" Function and use the "insert_many()" Functin to insert 
# into the collections.
movies_collection.insert_many(movies_data_frame.to_dict('records'))
ratings_collection.insert_many(ratings_data_frame.to_dict('records'))
tags_collection.insert_many(tags_data_frame.to_dict('records'))
print("Insert successful!")

Insert successful!

In [3]:
# To see more movies inserted in the Movies Collection, adjust the limited numerical value "10" that would print out and return the first 10 records
# in the movies collection from the Commas-Separated Value CSV File "movies.csv" to any other numerical value greater than 10 up to the maximum limit 
# of 9742 records returned. 
print("Movies Collection:")
print("-----------------------------------------------------------------------------------------------------------------------------------------------")
for item in movies_collection.find().limit(10):
    print(item['movieId'],item['title'])
print('\n')

# To see more movies inserted in the Ratings Collection, adjust the limited numerical value "10" that would print out and return the first 10 records
# in the movies collection from the Commas-Separated Value CSV File "ratings.csv" to any other numerical value greater than 10 up to the maximum limit
# of 100836 records returned.
print("Ratings Collection:")
print("-----------------------------------------------------------------------------------------------------------------------------------------------")
for item in ratings_collection.find().limit(10):
    print(item['movieId'], item['rating'])
print('\n')

# To see more movies inserted in the Tags Collection, adjust the limited numerical value "10" that would print out and return the first 10 records
# in the movies collection from the Commas-Separated Value CSV File "tags.csv" to any other numerical value greater than 10 up to the maximum limit
# of 3683 records returned.
print("Tags Collection:")
print("-----------------------------------------------------------------------------------------------------------------------------------------------")
for item in tags_collection.find().limit(10):
    print(item['movieId'], item['tag'])
print('\n')

Movies Collection:
-----------------------------------------------------------------------------------------------------------------------------------------------
1 Toy Story (1995)
2 Jumanji (1995)
3 Grumpier Old Men (1995)
4 Waiting to Exhale (1995)
5 Father of the Bride Part II (1995)
6 Heat (1995)
7 Sabrina (1995)
8 Tom and Huck (1995)
9 Sudden Death (1995)
10 GoldenEye (1995)


Ratings Collection:
-----------------------------------------------------------------------------------------------------------------------------------------------
1 4.0
3 4.0
6 4.0
47 5.0
50 5.0
70 3.0
101 5.0
110 4.0
151 5.0
157 5.0


Tags Collection:
-----------------------------------------------------------------------------------------------------------------------------------------------
60756 funny
60756 Highly quotable
60756 will ferrell
89774 Boxing story
89774 MMA
89774 Tom Hardy
106782 drugs
106782 Leonardo DiCaprio
106782 Martin Scorsese
48516 way too long

In [4]:
##############################################################################################################################################
# Problem 4: Next, write a program to add five movies that you have watched this year, or you would like to watch to the collection "movies" #
# that is in this case the "movies_collection". Make sure that you assign unique movie IDs and specify the genres.                           #
##############################################################################################################################################

# First, retrieve the largest "movieId" and then increment the numeric value of "movieId" by 1 in order to get the latest "movieId".
new_id = movies_collection.find_one(sort={"movieId":-1})["movieId"]+1

# Use the "insert_many" Function to insert, in other words add, five movies into the movies collection.
movies_collection.insert_many([
    {
       "movieId": new_id,
        "title": "Yugioh! 3D Bonds Beyond Time (2010)",
        "genres": "Animation|Fantasy"
    },
    {
        "movieId": new_id+1,
        "title": "Pokémon Detective Pikachu (2019)",
        "genres": "Action|Adventure|Comedy|Family|Mystery|Science Fiction",
    },
    {
        "movieId": new_id+2,
        "title": "Sonic the Hedgehog (2020)",
        "genres": "Adventure|Comedy|Fantasy|Science Fiction"
    },
    {
        "movieId": new_id+3,
        "title": "Pokémon the Movie: Secrets of the Jungle (2020)",
        "genres": "Adventure|Animation|Anime|Children"
    },
    {
        "movieId": new_id+4,
        "title": "Tom & Jerry (2021)",
        "genres": "Adventure|Animation|Comedy"
    }
])

InsertManyResult([ObjectId('663426a2a409a26cc14da828'), ObjectId('663426a2a409a26cc14da829'), ObjectId('663426a2a409a26cc14da82a'), ObjectId('663426a2a409a26cc14da82b'), ObjectId('663426a2a409a26cc14da82c')], acknowledged=True)

In [5]:
#####################################################################################################################################################
# Problem 5 Part 1: Corresponding to the movies that are added, write a program to add some suitable ratings to the collection "ratings" that is in #
# this case the "ratings_collection". Make sure that you use a unique userid for yourself.                                                          #                                                                                          #
#####################################################################################################################################################

# Use the same "movieId" values to attach ratings to the movies entered and in addition use the "time.time()" Function to automate the creation of 
# timestamps.
ratings_collection.insert_many([
    {
        "userId": 1247,
        "movieId": new_id,
        "rating": 3.2,
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+1,
        "rating": 3.3,
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+2,
        "rating": 3.3,
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+3,
        "rating": 3.2,
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+4,
        "rating": 2.6,
        "timestamp": int(time.time())
    }
])

InsertManyResult([ObjectId('663426a2a409a26cc14da82d'), ObjectId('663426a2a409a26cc14da82e'), ObjectId('663426a2a409a26cc14da82f'), ObjectId('663426a2a409a26cc14da830'), ObjectId('663426a2a409a26cc14da831')], acknowledged=True)

In [6]:
####################################################################################################################################################
# Problem 5 Part 2: Corresponding to the movies that are added, write a program to add some suitable tags to the collection "tags" that is in this #
# case the "tags_collection". Make sure that you use a unique userid for yourself.                                                                 #                                                                                          #
####################################################################################################################################################

# Add tags to the movies using the same "movieId" and timestamp system as the ratings.
tags_collection.insert_many([
    {
        "userId": 1247,
        "movieId": new_id,
        "tag": "4Kids Entertainment",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id,
        "tag": "Studio Gallop",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id,
        "tag": "Yugioh! 10 Year Anniversary",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id,
        "tag": "Dan Green",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+1,
        "tag": "Ryan Reynolds",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+1,
        "tag": "Pikachu",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+1,
        "tag": "Pokemon",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+1,
        "tag": "Nintendo",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+2,
        "tag": "Sega",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+2,
        "tag": "Sonic",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+2,
        "tag": "Jim Carrey",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+2,
        "tag": "highest-grossing video game film adaptation",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+3,
        "tag": "Ash Ketchum",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+3,
        "tag": "Franchise Film Series",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+3,
        "tag": "Sarah Natochenny",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+3,
        "tag": "Netflix",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+4,
        "tag": "Tom Cat",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+4,
        "tag": "Warner Bros. Pictures Animation",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+4,
        "tag": "Jerry Mouse",
        "timestamp": int(time.time())
    },
    {
        "userId": 1247,
        "movieId": new_id+4,
        "tag": "Ken Jeong",
        "timestamp": int(time.time())
    }  
])

InsertManyResult([ObjectId('663426a2a409a26cc14da832'), ObjectId('663426a2a409a26cc14da833'), ObjectId('663426a2a409a26cc14da834'), ObjectId('663426a2a409a26cc14da835'), ObjectId('663426a2a409a26cc14da836'), ObjectId('663426a2a409a26cc14da837'), ObjectId('663426a2a409a26cc14da838'), ObjectId('663426a2a409a26cc14da839'), ObjectId('663426a2a409a26cc14da83a'), ObjectId('663426a2a409a26cc14da83b'), ObjectId('663426a2a409a26cc14da83c'), ObjectId('663426a2a409a26cc14da83d'), ObjectId('663426a2a409a26cc14da83e'), ObjectId('663426a2a409a26cc14da83f'), ObjectId('663426a2a409a26cc14da840'), ObjectId('663426a2a409a26cc14da841'), ObjectId('663426a2a409a26cc14da842'), ObjectId('663426a2a409a26cc14da843'), ObjectId('663426a2a409a26cc14da844'), ObjectId('663426a2a409a26cc14da845')], acknowledged=True)

In [7]:
# Create a for() Loop to display the movies one by one in order to show that the data was correctly inserted.
for i_index in range(new_id, new_id+5):

    # Use the "find_one()" Function to retrieve all of the information in the "movies_collection", "ratings_collection", and "tags_collection"
    # by "movieId".
    movie = movies_collection.find_one({"movieId": i_index})
    rating = ratings_collection.find_one({"movieId": i_index})
    tag = tags_collection.find({"movieId": i_index})

    # Print each element separately.
    print("Title: ", movie["title"])
    print("Genres: ", movie["genres"].replace("|", ", "))
    print("Rating: ", rating["rating"])
    print("Tags: ", end="")
    for tag_object in tag:
        print("\t", tag_object["tag"])
    print("-------------------------------------------------------------------------------------------------------------------------------------------")

Title:  Yugioh! 3D Bonds Beyond Time (2010)
Genres:  Animation, Fantasy
Rating:  3.2
Tags: 	 4Kids Entertainment
	 Studio Gallop
	 Yugioh! 10 Year Anniversary
	 Dan Green
-------------------------------------------------------------------------------------------------------------------------------------------
Title:  Pokémon Detective Pikachu (2019)
Genres:  Action, Adventure, Comedy, Family, Mystery, Science Fiction
Rating:  3.3
Tags: 	 Ryan Reynolds
	 Pikachu
	 Pokemon
	 Nintendo
-------------------------------------------------------------------------------------------------------------------------------------------
Title:  Sonic the Hedgehog (2020)
Genres:  Adventure, Comedy, Fantasy, Science Fiction
Rating:  3.3
Tags: 	 Sega
	 Sonic
	 Jim Carrey
	 highest-grossing video game film adaptation
-------------------------------------------------------------------------------------------------------------------------------------------
Title:  Pokémon the Movie: Secrets of the Jungle (2020)
Genres:  Adventure, Animation, Anime, Children
Rating:  3.2
Tags: 	 Ash Ketchum
	 Franchise Film Series
	 Sarah Natochenny
	 Netflix
-------------------------------------------------------------------------------------------------------------------------------------------
Title:  Tom & Jerry (2021)
Genres:  Adventure, Animation, Comedy
Rating:  2.6
Tags: 	 Tom Cat
	 Warner Bros. Pictures Animation
	 Jerry Mouse
	 Ken Jeong
-------------------------------------------------------------------------------------------------------------------------------------------

In [8]:
##################################################################################
# Problem 6 Part a: Develop code to find the number of movies released per year. #
##################################################################################

# Use an Aggregation Pipeline consisting of a project, group, and sort aggregate in order to produce a list of "years" and the number of movies released
# in those "years".
years = movies_collection.aggregate([
    {"$project": {
        "year": {
            "$regexFind": {"input": "$title", "regex": "\\(([0-9]{4})\\)"}
        }
    }},
    {"$group": {"_id": "$year.captures", "count": {"$sum": 1}}},
    {"$sort": {"_id": 1}}
])
list(years)

[{'_id': None, 'count': 13},
 {'_id': ['1902'], 'count': 1},
 {'_id': ['1903'], 'count': 1},
 {'_id': ['1908'], 'count': 1},
 {'_id': ['1915'], 'count': 1},
 {'_id': ['1916'], 'count': 4},
 {'_id': ['1917'], 'count': 1},
 {'_id': ['1919'], 'count': 1},
 {'_id': ['1920'], 'count': 2},
 {'_id': ['1921'], 'count': 1},
 {'_id': ['1922'], 'count': 1},
 {'_id': ['1923'], 'count': 4},
 {'_id': ['1924'], 'count': 5},
 {'_id': ['1925'], 'count': 4},
 {'_id': ['1926'], 'count': 5},
 {'_id': ['1927'], 'count': 7},
 {'_id': ['1928'], 'count': 4},
 {'_id': ['1929'], 'count': 4},
 {'_id': ['1930'], 'count': 5},
 {'_id': ['1931'], 'count': 14},
 {'_id': ['1932'], 'count': 9},
 {'_id': ['1933'], 'count': 12},
 {'_id': ['1934'], 'count': 11},
 {'_id': ['1935'], 'count': 13},
 {'_id': ['1936'], 'count': 18},
 {'_id': ['1937'], 'count': 16},
 {'_id': ['1938'], 'count': 15},
 {'_id': ['1939'], 'count': 23},
 {'_id': ['1940'], 'count': 25},
 {'_id': ['1941'], 'count': 18},
 {'_id': ['1942'], 'count': 23},
 {'_id': ['1943'], 'count': 10},
 {'_id': ['1944'], 'count': 16},
 {'_id': ['1945'], 'count': 17},
 {'_id': ['1946'], 'count': 23},
 {'_id': ['1947'], 'count': 20},
 {'_id': ['1948'], 'count': 20},
 {'_id': ['1949'], 'count': 25},
 {'_id': ['1950'], 'count': 21},
 {'_id': ['1951'], 'count': 22},
 {'_id': ['1952'], 'count': 16},
 {'_id': ['1953'], 'count': 30},
 {'_id': ['1954'], 'count': 23},
 {'_id': ['1955'], 'count': 36},
 {'_id': ['1956'], 'count': 30},
 {'_id': ['1957'], 'count': 33},
 {'_id': ['1958'], 'count': 31},
 {'_id': ['1959'], 'count': 37},
 {'_id': ['1960'], 'count': 37},
 {'_id': ['1961'], 'count': 34},
 {'_id': ['1962'], 'count': 40},
 {'_id': ['1963'], 'count': 39},
 {'_id': ['1964'], 'count': 43},
 {'_id': ['1965'], 'count': 47},
 {'_id': ['1966'], 'count': 42},
 {'_id': ['1967'], 'count': 42},
 {'_id': ['1968'], 'count': 42},
 {'_id': ['1969'], 'count': 35},
 {'_id': ['1970'], 'count': 33},
 {'_id': ['1971'], 'count': 47},
 {'_id': ['1972'], 'count': 39},
 {'_id': ['1973'], 'count': 59},
 {'_id': ['1974'], 'count': 45},
 {'_id': ['1975'], 'count': 42},
 {'_id': ['1976'], 'count': 44},
 {'_id': ['1977'], 'count': 63},
 {'_id': ['1978'], 'count': 59},
 {'_id': ['1979'], 'count': 69},
 {'_id': ['1980'], 'count': 89},
 {'_id': ['1981'], 'count': 92},
 {'_id': ['1982'], 'count': 87},
 {'_id': ['1983'], 'count': 83},
 {'_id': ['1984'], 'count': 101},
 {'_id': ['1985'], 'count': 126},
 {'_id': ['1986'], 'count': 139},
 {'_id': ['1987'], 'count': 153},
 {'_id': ['1988'], 'count': 165},
 {'_id': ['1989'], 'count': 142},
 {'_id': ['1990'], 'count': 147},
 {'_id': ['1991'], 'count': 147},
 {'_id': ['1992'], 'count': 167},
 {'_id': ['1993'], 'count': 198},
 {'_id': ['1994'], 'count': 237},
 {'_id': ['1995'], 'count': 259},
 {'_id': ['1996'], 'count': 276},
 {'_id': ['1997'], 'count': 260},
 {'_id': ['1998'], 'count': 258},
 {'_id': ['1999'], 'count': 263},
 {'_id': ['2000'], 'count': 283},
 {'_id': ['2001'], 'count': 294},
 {'_id': ['2002'], 'count': 311},
 {'_id': ['2003'], 'count': 279},
 {'_id': ['2004'], 'count': 279},
 {'_id': ['2005'], 'count': 273},
 {'_id': ['2006'], 'count': 295},
 {'_id': ['2007'], 'count': 284},
 {'_id': ['2008'], 'count': 269},
 {'_id': ['2009'], 'count': 282},
 {'_id': ['2010'], 'count': 248},
 {'_id': ['2011'], 'count': 254},
 {'_id': ['2012'], 'count': 233},
 {'_id': ['2013'], 'count': 239},
 {'_id': ['2014'], 'count': 278},
 {'_id': ['2015'], 'count': 274},
 {'_id': ['2016'], 'count': 218},
 {'_id': ['2017'], 'count': 147},
 {'_id': ['2018'], 'count': 41},
 {'_id': ['2019'], 'count': 1},
 {'_id': ['2020'], 'count': 2},
 {'_id': ['2021'], 'count': 1}]

In [9]:
##########################################################################
# Problem 6 Part b: Develop code to find the number of movies per genre. #
##########################################################################

# Use an Aggregation Pipeline consisting of a project and a split, unwind, group and sort aggregate in order to produce a list of "genres" and 
# compute the number of movies for each different type of genre. First, use the "project" aggregate and "split" aggregate to split the genres 
# on the '|' character, in other words, the Pipe Character. Second, use the "unwind" aggregate to split the array into separate documents. Third,
# use the "group" aggregate to create the count. Finally, use the "sort" aggregate to show the results for each "genre" type category in 
# alphabetical order. 
genre = movies_collection.aggregate([
    {"$project": {
        "genre": {
            "$split": ["$genres", "|"]
        }
    }},
    {"$unwind": "$genre"},
    {"$group": {"_id": "$genre", "count": {"$sum": 1}}},
    {"$sort": {"_id": 1}}
])
list(genre)

[{'_id': '(no genres listed)', 'count': 34},
 {'_id': 'Action', 'count': 1829},
 {'_id': 'Adventure', 'count': 1267},
 {'_id': 'Animation', 'count': 614},
 {'_id': 'Anime', 'count': 1},
 {'_id': 'Children', 'count': 665},
 {'_id': 'Comedy', 'count': 3759},
 {'_id': 'Crime', 'count': 1199},
 {'_id': 'Documentary', 'count': 440},
 {'_id': 'Drama', 'count': 4361},
 {'_id': 'Family', 'count': 1},
 {'_id': 'Fantasy', 'count': 781},
 {'_id': 'Film-Noir', 'count': 87},
 {'_id': 'Horror', 'count': 978},
 {'_id': 'IMAX', 'count': 158},
 {'_id': 'Musical', 'count': 334},
 {'_id': 'Mystery', 'count': 574},
 {'_id': 'Romance', 'count': 1596},
 {'_id': 'Sci-Fi', 'count': 980},
 {'_id': 'Science Fiction', 'count': 2},
 {'_id': 'Thriller', 'count': 1894},
 {'_id': 'War', 'count': 382},
 {'_id': 'Western', 'count': 167}]

In [10]:
###########################################################################
# Problem 6 Part c: Develop code to find the number of movies per rating. #
###########################################################################

# Use an Aggregation Pipeline consisting of a group aggregate to count the number of entries for each rating value and the sort aggregate to sort
# each rating value from the lowest rating value to the highest rating value.
rating = ratings_collection.aggregate([
    {"$group": {"_id": "$rating", "count": {"$sum": 1}}},
    {"$sort": {"_id": 1}}
])
list(rating)

[{'_id': 0.5, 'count': 1370},
 {'_id': 1.0, 'count': 2811},
 {'_id': 1.5, 'count': 1791},
 {'_id': 2.0, 'count': 7551},
 {'_id': 2.5, 'count': 5550},
 {'_id': 2.6, 'count': 1},
 {'_id': 3.0, 'count': 20047},
 {'_id': 3.2, 'count': 2},
 {'_id': 3.3, 'count': 2},
 {'_id': 3.5, 'count': 13136},
 {'_id': 4.0, 'count': 26818},
 {'_id': 4.5, 'count': 8551},
 {'_id': 5.0, 'count': 13211}]

In [11]:
#######################################################################
# Problem 6 Part d: Develop code to find the number of movies tagged. #
#######################################################################

# Use an Aggregation Pipeline by first using one "group" aggregate to group the movies by "movieId" to produce a set of unique movies and then 
# using a "group" aggregate to group by "None" so that the group would count all the lines as the same key value.
tag = tags_collection.aggregate([
    {"$group": {"_id": "$movieId", "count": {"$sum": 1}}},
    {"$group": {"_id": None, "count": {"$sum": 1}}}
])
list(tag)

[{'_id': None, 'count': 1577}]

In [12]:
################################################################
# Problem 6 Part e: Develop code to find the most popular tag. #
################################################################

# Use an Aggregation Pipeline consisting of a group, sort, and limit aggregate where first a "group" aggregate is used to count all of the tags,
# second a "sort" aggregate is used to sort the count for each different "tag" from the most popular tag to the least popular tag, and then
# finally, a "limit" aggregate is used to set the limit to the single most popular tag with the highest count value.
tag = tags_collection.aggregate([
    {"$group": {"_id": "$tag", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}},
    {"$limit": 1}
])
list(tag)

[{'_id': 'In Netflix queue', 'count': 131}]